# Discord Webhook URL (leave empty to disable)
discord-webhook: ""
attempts: 1
active-world: ""
players:
shared:
  health: 20.0
  food: 20
  exp: 0.0
  level: 0
  enable-health: true
  enable-food: true
  enable-exp: true
  enable-level: true
  enable-inventory: true
  inventory-id: ""